# Generated by Django 5.2.6 on 2025-09-26 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Activo')),
                ('codigo_interno', models.IntegerField(unique=True, verbose_name='Código Interno')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Actual')),
                ('vida_util', models.IntegerField(verbose_name='Vida Útil (años)')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Departamento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Divisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Divisa')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('tasa_cambio', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Tasa de Cambio')),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('nit', models.IntegerField(unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Permiso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Proveedor')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoDepreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Tipo de Depreciación',
                'verbose_name_plural': 'Tipos de Depreciación',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Ubicación')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('activo_fijo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.activofijo', verbose_name='Activo Fijo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categoriaactivo', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='DisposicionActivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Disposición')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('valor_disposicion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Disposición')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('activo_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activofijo', verbose_name='Activo Fijo')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.divisas', verbose_name='Divisa')),
            ],
            options={
                'verbose_name': 'Disposición de Activo',
                'verbose_name_plural': 'Disposiciones de Activos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField(unique=True, verbose_name='Cédula de Identidad')),
                ('apellido_p', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cargo', verbose_name='Cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.departamento', verbose_name='Departamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción Realizada')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('area_afectada', models.CharField(max_length=100, verbose_name='Área Afectada')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.empleado', verbose_name='Empleado que realiza')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.estado', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Impuesto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('disposicion_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disposicionactivos', verbose_name='Disposición de Activo')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Asignado')),
                ('categoria_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categoriaactivo', verbose_name='Categoría de Activo')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto',
                'verbose_name_plural': 'Detalles de Presupuesto',
            },
        ),
        migrations.CreateModel(
            name='ContratosProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiciones', models.TextField(verbose_name='Condiciones')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha Final')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado del Contrato')),
                ('activo_fijo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.activofijo', verbose_name='Activo Fijo Relacionado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.empleado', verbose_name='Empleado Responsable')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Contrato con Proveedor',
                'verbose_name_plural': 'Contratos con Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Reporte')),
                ('tipo_reporte', models.CharField(max_length=50, verbose_name='Tipo de Reporte')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.empleado', verbose_name='Empleado que genera')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='RevalorizacionActivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Revalorización')),
                ('nuevo_valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nuevo Valor')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('activo_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activofijo', verbose_name='Activo Fijo')),
            ],
            options={
                'verbose_name': 'Revalorización de Activo',
                'verbose_name_plural': 'Revalorizaciones de Activos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Rol')),
                ('permisos', models.ManyToManyField(blank=True, to='api.permisos', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.roles', verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='DepreciacionActivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Depreciación')),
                ('monto_depreciado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Depreciado')),
                ('activo_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activofijo', verbose_name='Activo Fijo')),
                ('tipo_depreciacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipodepreciacion', verbose_name='Tipo de Depreciación')),
            ],
            options={
                'verbose_name': 'Depreciación de Activo',
                'verbose_name_plural': 'Depreciaciones de Activos',
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('tipo_movimiento', models.CharField(max_length=50, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventario', verbose_name='Inventario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
    ]
