# Generated by Django 5.2.6 on 2025-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_poblar_roles_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(default='activo', max_length=10, verbose_name='Estado'),
        ),
    ]
