# Generated by Django 5.2.6 on 2025-10-08 18:37

from django.db import migrations

ESTADOS_INICIALES = [
    'Activo',
    'Inactivo',
    'En Mantenimiento',
    'De Baja',
    'En Reparación',
    'Vendido'
]

def poblar_estados(apps, schema_editor):
    """
    Crea los registros iniciales para el modelo Estado.
    """
    Estado = apps.get_model('api', 'Estado')
    for nombre_estado in ESTADOS_INICIALES:
        Estado.objects.get_or_create(nombre=nombre_estado)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proveedor_estado'),
    ]

    operations = [
        migrations.RunPython(poblar_estados),
    ]
